/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mygameant;

import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import mygameant.DataBase;
import mygameant.Register_Form;
import mygameant.Register_Form;
import mygameant.UserUI;

/**
 *
 * @author mikaelcuyugan
 */
public class Login_Form extends javax.swing.JFrame {
    public String userDB,passDB;
    int chances=3;
    /**
     * Creates new form LogInForm
     */
    public Login_Form() {
        initComponents();
        //txtPass.setEchoChar((char)0);
        try{
            File fontStyle = new File("src/fonts/ARCADECLASSIC.TTF");
            Font font = Font.createFont(Font.TRUETYPE_FONT,fontStyle).deriveFont(20f);
            Font fontLog = Font.createFont(Font.TRUETYPE_FONT,fontStyle).deriveFont(30f);
            Font fontTitle = Font.createFont(Font.TRUETYPE_FONT,fontStyle).deriveFont(17f);
            lblTitle.setFont(fontTitle);
            lblTitle1.setFont(fontTitle);
            lblTitle2.setFont(fontTitle);
            lblTitle4.setFont(fontTitle);
            lblLogin.setFont(fontLog);
            username.setFont(font);
            btnEnter.setFont(font);
            lblForEmail.setFont(font);
            lblForPass.setFont(font);
            lblNew.setFont(font);
            btnRegister.setFont(font);
            
        }catch(Exception e){
            e.printStackTrace();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlEmail = new javax.swing.JPanel();
        lblLogin = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        lblForEmail = new javax.swing.JLabel();
        txtusername = new javax.swing.JLabel();
        pnlEmail1 = new javax.swing.JPanel();
        signpassword = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        lblForPass = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        login = new javax.swing.JLabel();
        btnEnter = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblNew = new javax.swing.JLabel();
        lblRegister = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        lblTitle2 = new javax.swing.JLabel();
        lblTitle4 = new javax.swing.JLabel();
        lplSplash = new javax.swing.JLabel();
        lblBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login ata ");
        setBackground(new java.awt.Color(51, 51, 51));

        jPanel1.setBackground(new java.awt.Color(57, 84, 43));
        jPanel1.setPreferredSize(new java.awt.Dimension(814, 431));
        jPanel1.setLayout(null);

        pnlEmail.setBackground(new java.awt.Color(42, 27, 32));
        pnlEmail.setForeground(new java.awt.Color(255, 255, 255));

        lblLogin.setBackground(new java.awt.Color(42, 27, 32));
        lblLogin.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblLogin.setText("Login");

        username.setBackground(new java.awt.Color(42, 27, 32));
        username.setForeground(new java.awt.Color(153, 153, 153));
        username.setBorder(null);
        username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameFocusLost(evt);
            }
        });
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        lblForEmail.setBackground(new java.awt.Color(42, 27, 32));
        lblForEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblForEmail.setText("Username");

        txtusername.setBackground(new java.awt.Color(42, 27, 32));
        txtusername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Email.png"))); // NOI18N

        javax.swing.GroupLayout pnlEmailLayout = new javax.swing.GroupLayout(pnlEmail);
        pnlEmail.setLayout(pnlEmailLayout);
        pnlEmailLayout.setHorizontalGroup(
            pnlEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmailLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblForEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlEmailLayout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(225, 225, 225))
            .addGroup(pnlEmailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlEmailLayout.createSequentialGroup()
                    .addGap(53, 53, 53)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(157, Short.MAX_VALUE)))
        );
        pnlEmailLayout.setVerticalGroup(
            pnlEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(lblForEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(pnlEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlEmailLayout.createSequentialGroup()
                    .addGap(92, 92, 92)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(18, Short.MAX_VALUE)))
        );

        jPanel1.add(pnlEmail);
        pnlEmail.setBounds(380, 40, 440, 150);

        pnlEmail1.setBackground(new java.awt.Color(42, 27, 32));
        pnlEmail1.setForeground(new java.awt.Color(255, 255, 255));

        signpassword.setBackground(new java.awt.Color(42, 27, 32));
        signpassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Email.png"))); // NOI18N
        signpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                signpasswordFocusGained(evt);
            }
        });

        password.setBackground(new java.awt.Color(42, 27, 32));
        password.setForeground(new java.awt.Color(153, 153, 153));
        password.setBorder(null);
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });

        lblForPass.setBackground(new java.awt.Color(42, 27, 32));
        lblForPass.setForeground(new java.awt.Color(255, 255, 255));
        lblForPass.setText("Password");

        javax.swing.GroupLayout pnlEmail1Layout = new javax.swing.GroupLayout(pnlEmail1);
        pnlEmail1.setLayout(pnlEmail1Layout);
        pnlEmail1Layout.setHorizontalGroup(
            pnlEmail1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmail1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(pnlEmail1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEmail1Layout.createSequentialGroup()
                        .addComponent(lblForPass, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(326, 326, 326))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEmail1Layout.createSequentialGroup()
                        .addComponent(signpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(pnlEmail1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlEmail1Layout.createSequentialGroup()
                    .addGap(52, 52, 52)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(48, Short.MAX_VALUE)))
        );
        pnlEmail1Layout.setVerticalGroup(
            pnlEmail1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmail1Layout.createSequentialGroup()
                .addComponent(lblForPass)
                .addGap(18, 18, 18)
                .addComponent(signpassword)
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(pnlEmail1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlEmail1Layout.createSequentialGroup()
                    .addGap(44, 44, 44)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(55, Short.MAX_VALUE)))
        );

        jPanel1.add(pnlEmail1);
        pnlEmail1.setBounds(380, 190, 440, 140);

        jPanel2.setBackground(new java.awt.Color(42, 27, 32));

        login.setBackground(new java.awt.Color(42, 27, 32));
        login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Button (1).png"))); // NOI18N

        btnEnter.setBackground(new java.awt.Color(42, 27, 32));
        btnEnter.setForeground(new java.awt.Color(255, 255, 255));
        btnEnter.setText("ENTER");
        btnEnter.setBorder(null);
        btnEnter.setBorderPainted(false);
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(78, 78, 78)
                    .addComponent(btnEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(84, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(login)
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addComponent(btnEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(43, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(376, 320, 440, 110);

        jPanel3.setBackground(new java.awt.Color(42, 27, 32));

        lblNew.setBackground(new java.awt.Color(42, 27, 32));
        lblNew.setForeground(new java.awt.Color(255, 255, 255));
        lblNew.setText("Register");

        lblRegister.setBackground(new java.awt.Color(42, 27, 32));
        lblRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Button (1).png"))); // NOI18N

        btnRegister.setBackground(new java.awt.Color(42, 27, 32));
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("CREATE  A  NEW  ACCOUNT");
        btnRegister.setBorder(null);
        btnRegister.setBorderPainted(false);
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(lblNew, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(lblRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(130, 130, 130)
                    .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(56, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNew)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(55, 55, 55)
                    .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(30, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(330, 460, 460, 120);

        jPanel4.setBackground(new java.awt.Color(42, 27, 32));

        lblTitle.setBackground(new java.awt.Color(42, 27, 32));
        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("That  time  I  went  hunting  and  pissed  on  ");

        lblTitle1.setBackground(new java.awt.Color(42, 27, 32));
        lblTitle1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle1.setText("a  magical  wizard  frog  and  got ");

        lblTitle2.setBackground(new java.awt.Color(42, 27, 32));
        lblTitle2.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblTitle2.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle2.setText("teleported  into  a  magical  cursed ");

        lblTitle4.setBackground(new java.awt.Color(42, 27, 32));
        lblTitle4.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle4.setText("forest");

        lplSplash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/spbg.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblTitle1))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblTitle2))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(lblTitle4))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(lplSplash)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTitle2)
                .addGap(26, 26, 26)
                .addComponent(lblTitle4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lplSplash)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(50, 50, 340, 540);

        lblBG.setBackground(new java.awt.Color(42, 27, 32));
        lblBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1.png"))); // NOI18N
        jPanel1.add(lblBG);
        lblBG.setBounds(0, 10, 840, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 864, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusLost
        //        if(String.valueOf(txtPass.getPassword()).equals("")){
            //
            //            txtPass.setEchoChar((char)0);
            //            txtPass.setText("Password");
            //            txtPass.setForeground(new Color(153,153,153));
            //
            //        }
    }//GEN-LAST:event_passwordFocusLost

    private void signpasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signpasswordFocusGained
        //        if(String.valueOf(txtPass.getPassword()).equals("Password")){
            //
            //            txtPass.setText("");
            //            txtPass.setForeground(new Color(153,153,153));
            //            txtPass.setEchoChar('•');
            //        }
    }//GEN-LAST:event_signpasswordFocusGained

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusLost
        //        if(txtEmail.getText().equals("")){
            //
            //            txtEmail.setText("Email");
            //            txtEmail.setForeground(new Color(153,153,153));
            //        }
    }//GEN-LAST:event_usernameFocusLost

    private void usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusGained
        //        if(txtEmail.getText().equals("Email")){
            //
            //            txtEmail.setText("");
            //            txtEmail.setForeground(new Color(153,153,153));
            //        }
    }//GEN-LAST:event_usernameFocusGained

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        Register_Form RegisterForm = new Register_Form();
        RegisterForm.setVisible(true);
        RegisterForm.pack();
        RegisterForm.setLocationRelativeTo(this);
        dispose();
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
        // TODO add your handling code here:
        DataBase connect = new DataBase();
         String user = username.getText();
         String pass = new String(password.getPassword());
         if(!user.isEmpty()&&!pass.isEmpty()){
            try {
                Connection con = connect.connection();
                Statement st_user = con.createStatement();
                Statement st_pass = con.createStatement();
                ResultSet rs_user = st_user.executeQuery("SELECT * FROM `user` WHERE username='"+user+"'");
                ResultSet rs_pass = st_pass.executeQuery("SELECT * FROM `user` WHERE password='"+pass+"'");

                while(rs_pass.next()){
                    passDB = rs_pass.getString("password");
                }
                while(rs_user.next()){
                    userDB = rs_user.getString("username");
                }
                if(userDB != null && passDB != null && userDB.equals(user)&&passDB.equals(pass)){
                    UserUI userui = new UserUI();
                    userui.setVisible(true);
                    userui.pack();
                    userui.playerName.setText(userDB);
                    userui.setLocationRelativeTo(this);
                    dispose();
                }else if(passDB == null ||userDB == null ){
                    if(chances==0){
                        JOptionPane.showMessageDialog(rootPane, "Goodbye! Try again later!", "Error!", JOptionPane.ERROR_MESSAGE);
                        this.dispose();
                    }else{
                        JOptionPane.showMessageDialog(rootPane, "Password or Username Inccorect( "+chances+" Tries Left! )", "Error!", JOptionPane.ERROR_MESSAGE);
                        chances--;
                    }
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Username not Registered", "Error!", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception ex) {
                System.out.println("error"+ex.getMessage());
            }
         }else if(user.isEmpty()&&!pass.isEmpty()){
             JOptionPane.showMessageDialog(rootPane, "Username Required", "Error!", JOptionPane.ERROR_MESSAGE);    
         }else if(!user.isEmpty()&&pass.isEmpty()){
             JOptionPane.showMessageDialog(rootPane, "Password Required", "Error!", JOptionPane.ERROR_MESSAGE);    
         }else{
             JOptionPane.showMessageDialog(rootPane, "Username and Password is Required", "Error!", JOptionPane.ERROR_MESSAGE);    
           }
    }//GEN-LAST:event_btnEnterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnter;
    private javax.swing.JButton btnRegister;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblBG;
    private javax.swing.JLabel lblForEmail;
    private javax.swing.JLabel lblForPass;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblNew;
    private javax.swing.JLabel lblRegister;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JLabel lblTitle4;
    private javax.swing.JLabel login;
    private javax.swing.JLabel lplSplash;
    private javax.swing.JPasswordField password;
    private javax.swing.JPanel pnlEmail;
    private javax.swing.JPanel pnlEmail1;
    private javax.swing.JLabel signpassword;
    private javax.swing.JLabel txtusername;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
