/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mygameant;

import java.awt.*;
import java.io.File;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JOptionPane;
import mygameant.DataBase;

/**
 *
 * @author mikaelcuyugan
 */
public class Register_Form extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register_Form() {
        initComponents();
        try{
            File fontStyle = new File("src/fonts/ARCADECLASSIC.TTF");
            Font font = Font.createFont(Font.TRUETYPE_FONT,fontStyle).deriveFont(20f);
            Font fontLog = Font.createFont(Font.TRUETYPE_FONT,fontStyle).deriveFont(30f);
            Font fontTitle = Font.createFont(Font.TRUETYPE_FONT,fontStyle).deriveFont(17f);
            lblTitle.setFont(fontTitle);
            lblTitle1.setFont(fontTitle);
            lblTitle2.setFont(fontTitle);
            lblTitle4.setFont(fontTitle);
            lblRegister.setFont(fontLog);
            username.setFont(font);
            login.setFont(font);
            lblForEmail.setFont(font);
            lblForPass.setFont(font);
            lblForConPass.setFont(font);
            register1.setFont(font);
        }catch(Exception e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlEmail = new javax.swing.JPanel();
        lblRegister = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        lblForEmail = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        pnlEmail1 = new javax.swing.JPanel();
        lblPass = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        lblForPass = new javax.swing.JLabel();
        pnlEmail3 = new javax.swing.JPanel();
        pngConPass = new javax.swing.JLabel();
        confirmPass = new javax.swing.JPasswordField();
        lblForConPass = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblEnter = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        register1 = new javax.swing.JButton();
        lblEntasd = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        lblTitle2 = new javax.swing.JLabel();
        lblTitle4 = new javax.swing.JLabel();
        lplSplash = new javax.swing.JLabel();
        lblBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(57, 84, 43));
        jPanel1.setPreferredSize(new java.awt.Dimension(814, 431));
        jPanel1.setLayout(null);

        pnlEmail.setBackground(new java.awt.Color(42, 27, 32));
        pnlEmail.setForeground(new java.awt.Color(255, 255, 255));

        lblRegister.setBackground(new java.awt.Color(42, 27, 32));
        lblRegister.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblRegister.setForeground(new java.awt.Color(255, 255, 255));
        lblRegister.setText("Register");

        username.setBackground(new java.awt.Color(42, 27, 32));
        username.setForeground(new java.awt.Color(153, 153, 153));
        username.setBorder(null);
        username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameFocusLost(evt);
            }
        });
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        lblForEmail.setBackground(new java.awt.Color(42, 27, 32));
        lblForEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblForEmail.setText("Username");

        lblEmail.setBackground(new java.awt.Color(42, 27, 32));
        lblEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Email.png"))); // NOI18N

        javax.swing.GroupLayout pnlEmailLayout = new javax.swing.GroupLayout(pnlEmail);
        pnlEmail.setLayout(pnlEmailLayout);
        pnlEmailLayout.setHorizontalGroup(
            pnlEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmailLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(pnlEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEmailLayout.createSequentialGroup()
                        .addGroup(pnlEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblForEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlEmailLayout.createSequentialGroup()
                                .addGap(161, 161, 161)
                                .addComponent(lblRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(100, 100, 100))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEmailLayout.createSequentialGroup()
                        .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(pnlEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlEmailLayout.createSequentialGroup()
                    .addGap(53, 53, 53)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(47, Short.MAX_VALUE)))
        );
        pnlEmailLayout.setVerticalGroup(
            pnlEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(lblForEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pnlEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlEmailLayout.createSequentialGroup()
                    .addGap(92, 92, 92)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(18, Short.MAX_VALUE)))
        );

        jPanel1.add(pnlEmail);
        pnlEmail.setBounds(380, 40, 440, 150);

        pnlEmail1.setBackground(new java.awt.Color(42, 27, 32));
        pnlEmail1.setForeground(new java.awt.Color(255, 255, 255));

        lblPass.setBackground(new java.awt.Color(42, 27, 32));
        lblPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Email.png"))); // NOI18N
        lblPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblPassFocusGained(evt);
            }
        });

        password.setBackground(new java.awt.Color(42, 27, 32));
        password.setForeground(new java.awt.Color(153, 153, 153));
        password.setBorder(null);
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });

        lblForPass.setBackground(new java.awt.Color(42, 27, 32));
        lblForPass.setForeground(new java.awt.Color(255, 255, 255));
        lblForPass.setText("Password");

        javax.swing.GroupLayout pnlEmail1Layout = new javax.swing.GroupLayout(pnlEmail1);
        pnlEmail1.setLayout(pnlEmail1Layout);
        pnlEmail1Layout.setHorizontalGroup(
            pnlEmail1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEmail1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(pnlEmail1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPass, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlEmail1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lblForPass, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(pnlEmail1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlEmail1Layout.createSequentialGroup()
                    .addGap(52, 52, 52)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(48, Short.MAX_VALUE)))
        );
        pnlEmail1Layout.setVerticalGroup(
            pnlEmail1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmail1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblForPass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPass)
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(pnlEmail1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlEmail1Layout.createSequentialGroup()
                    .addGap(44, 44, 44)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(15, Short.MAX_VALUE)))
        );

        jPanel1.add(pnlEmail1);
        pnlEmail1.setBounds(380, 190, 440, 100);

        pnlEmail3.setBackground(new java.awt.Color(42, 27, 32));
        pnlEmail3.setForeground(new java.awt.Color(255, 255, 255));

        pngConPass.setBackground(new java.awt.Color(42, 27, 32));
        pngConPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Email.png"))); // NOI18N
        pngConPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pngConPassFocusGained(evt);
            }
        });

        confirmPass.setBackground(new java.awt.Color(42, 27, 32));
        confirmPass.setForeground(new java.awt.Color(153, 153, 153));
        confirmPass.setBorder(null);
        confirmPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                confirmPassFocusLost(evt);
            }
        });

        lblForConPass.setBackground(new java.awt.Color(42, 27, 32));
        lblForConPass.setForeground(new java.awt.Color(255, 255, 255));
        lblForConPass.setText("Confirm Password");

        javax.swing.GroupLayout pnlEmail3Layout = new javax.swing.GroupLayout(pnlEmail3);
        pnlEmail3.setLayout(pnlEmail3Layout);
        pnlEmail3Layout.setHorizontalGroup(
            pnlEmail3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmail3Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(pnlEmail3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEmail3Layout.createSequentialGroup()
                        .addComponent(lblForConPass, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEmail3Layout.createSequentialGroup()
                        .addComponent(pngConPass, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(pnlEmail3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlEmail3Layout.createSequentialGroup()
                    .addGap(52, 52, 52)
                    .addComponent(confirmPass, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(48, Short.MAX_VALUE)))
        );
        pnlEmail3Layout.setVerticalGroup(
            pnlEmail3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmail3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblForConPass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pngConPass)
                .addContainerGap(11, Short.MAX_VALUE))
            .addGroup(pnlEmail3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlEmail3Layout.createSequentialGroup()
                    .addGap(44, 44, 44)
                    .addComponent(confirmPass, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(15, Short.MAX_VALUE)))
        );

        jPanel1.add(pnlEmail3);
        pnlEmail3.setBounds(370, 290, 440, 100);

        jPanel2.setBackground(new java.awt.Color(42, 27, 32));

        lblEnter.setBackground(new java.awt.Color(42, 27, 32));
        lblEnter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Button (1).png"))); // NOI18N

        login.setBackground(new java.awt.Color(42, 27, 32));
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("Login Now");
        login.setBorder(null);
        login.setBorderPainted(false);
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lblEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(106, 106, 106)
                    .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(108, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEnter)
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(35, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(380, 480, 440, 100);

        jPanel3.setBackground(new java.awt.Color(42, 27, 32));

        register1.setBackground(new java.awt.Color(42, 27, 32));
        register1.setForeground(new java.awt.Color(255, 255, 255));
        register1.setText("Register");
        register1.setBorder(null);
        register1.setBorderPainted(false);
        register1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register1ActionPerformed(evt);
            }
        });

        lblEntasd.setBackground(new java.awt.Color(42, 27, 32));
        lblEntasd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Button (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(register1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(23, Short.MAX_VALUE)
                    .addComponent(lblEntasd, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(35, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(register1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEntasd, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(400, 400, 420, 80);

        jPanel4.setBackground(new java.awt.Color(42, 27, 32));

        lblTitle.setBackground(new java.awt.Color(42, 27, 32));
        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("That  time  I  went  hunting  and  pissed  on  ");

        lblTitle1.setBackground(new java.awt.Color(42, 27, 32));
        lblTitle1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle1.setText("a  magical  wizard  frog  and  got ");

        lblTitle2.setBackground(new java.awt.Color(42, 27, 32));
        lblTitle2.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblTitle2.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle2.setText("teleported  into  a  magical  cursed ");

        lblTitle4.setBackground(new java.awt.Color(42, 27, 32));
        lblTitle4.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle4.setText("forest");

        lplSplash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/spbg.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTitle2)
                            .addComponent(lblTitle1)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitle))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(lblTitle4))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(lplSplash)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTitle2)
                .addGap(28, 28, 28)
                .addComponent(lblTitle4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lplSplash))
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(50, 50, 330, 540);

        lblBG.setBackground(new java.awt.Color(42, 27, 32));
        lblBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1.png"))); // NOI18N
        jPanel1.add(lblBG);
        lblBG.setBounds(0, 10, 840, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 864, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusGained
        //        if(txtEmail.getText().equals("Email")){
            //
            //            txtEmail.setText("");
            //            txtEmail.setForeground(new Color(153,153,153));
            //        }
    }//GEN-LAST:event_usernameFocusGained

    private void usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusLost
        //        if(txtEmail.getText().equals("")){
            //
            //            txtEmail.setText("Email");
            //            txtEmail.setForeground(new Color(153,153,153));
            //        }
    }//GEN-LAST:event_usernameFocusLost

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void lblPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblPassFocusGained
        //        if(String.valueOf(txtPass.getPassword()).equals("Password")){
            //
            //            txtPass.setText("");
            //            txtPass.setForeground(new Color(153,153,153));
            //            txtPass.setEchoChar('•');
            //        }
    }//GEN-LAST:event_lblPassFocusGained

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusLost
        //        if(String.valueOf(txtPass.getPassword()).equals("")){
            //
            //            txtPass.setEchoChar((char)0);
            //            txtPass.setText("Password");
            //            txtPass.setForeground(new Color(153,153,153));
            //
            //        }
    }//GEN-LAST:event_passwordFocusLost

    private void pngConPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pngConPassFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_pngConPassFocusGained

    private void confirmPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirmPassFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmPassFocusLost

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        Login_Form LoginForm = new Login_Form();
        LoginForm.setVisible(true);
        LoginForm.pack();
        LoginForm.setLocationRelativeTo(this);
        dispose();
    }//GEN-LAST:event_loginActionPerformed

    private void register1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register1ActionPerformed
        // TODO add your handling code here:
        DataBase connect = new DataBase();
        String user = username.getText();
         String pass = new String(password.getPassword());
         String repass = new String(confirmPass.getPassword());
        try{
            if(user.isEmpty()||pass.isEmpty()||repass.isEmpty()){
                JOptionPane.showMessageDialog(rootPane, "Please Enter Username and Password", "Error!", JOptionPane.ERROR_MESSAGE);
            }else if(!pass.equals(repass)){
                JOptionPane.showMessageDialog(rootPane, "Password Doesnt Match", "Error!", JOptionPane.ERROR_MESSAGE);
            }else{
                Connection con = connect.connection();
                Statement st = con.createStatement();
                st.execute("INSERT INTO user(username,password) VALUES('"+user+"','"+pass+"')");
                JOptionPane.showMessageDialog(rootPane, "You are Now Registered!", "Welcome", JOptionPane.INFORMATION_MESSAGE);
                username.setText("");
                password.setText("");
                confirmPass.setText("");
            }
        }catch(Exception e){
            System.out.println("Error!"+e.getMessage());
        }
    }//GEN-LAST:event_register1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirmPass;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblBG;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEntasd;
    private javax.swing.JLabel lblEnter;
    private javax.swing.JLabel lblForConPass;
    private javax.swing.JLabel lblForEmail;
    private javax.swing.JLabel lblForPass;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblRegister;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JLabel lblTitle4;
    private javax.swing.JButton login;
    private javax.swing.JLabel lplSplash;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel pngConPass;
    private javax.swing.JPanel pnlEmail;
    private javax.swing.JPanel pnlEmail1;
    private javax.swing.JPanel pnlEmail3;
    private javax.swing.JButton register1;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
